project:
  type: website
  output-dir: docs

jupyter: python3

#execute:
#  freeze: auto

website:

  page-navigation: true
  repo-url: https://github.com
  
  reader-mode: false
  back-to-top-navigation: true

  navbar:
    title: 'Home'
  
    background: dark
#    foreground: secondary
    search: false

    tools:
      - icon: linkedin
        text: Linkedin
        href: https://linkedin.com
#      - icon: github
#        text: GitHub
#        href: https://github.com
      - icon: envelope
        text: Email
        href: mailto:rams9795@gmail.com
        

    left:
      - text: "Projects' overview"
        file: overview.qmd
   
      - text: "Projects"
        file: projects/MNIST/MNIST.qmd


        
        

  sidebar:

    
    - title: "Projects' overview"
    
      style: "floating"
      alignment: left
      border: true
#    background: light
      search: false
      
      contents:
        - section: "Overview of the projects"
          contents:
            - overview.qmd
            - tutorial-2.qmd
            - tutorial-3.qmd

    - title: "Projects"
    
      contents:
        - section: "Projects"
          contents:
            - projects/MNIST/MNIST.qmd
            - project2.qmd
            - project3.qmd
 

format:
  html:
    theme: 
      - cosmo
      - styles.scss
    fontsize: 16px
#    monofont: Source Sans Pro, sans-serif

  

    
    toc: true
    toc-title: Table of contents
    
    smooth-scroll: true
    anchor-sections: true
    number-sections: true
    page-layout: article
    
    code-copy: false
    code-fold: show
    code-overflow: wrap

      
    
    
    
    



