project:
  type: website
  output-dir: docs

jupyter: python3

website:

  page-navigation: true
  repo-url: https://github.com
  
  reader-mode: true
  back-to-top-navigation: true

  navbar:
    title: 'Home'
  
    background: dark
    foreground: secondary
    search: true
    tools:
      - icon: linkedin
        href: https://linkedin.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com
          - text: Report a Bug
            url:  https://bugs.com
    left:
      - text: "Projects' overview"
        file: overview.qmd
   
      - text: "Projects"
        file: MNIST.qmd


        
        

  sidebar:

    
    - title: "Projects' overview"
    
      style: "floating"
      alignment: left
      border: true
#    background: light
      search: true
      
      contents:
        - section: "Overview of the projects"
          contents:
            - overview.qmd
            - tutorial-2.qmd
            - tutorial-3.qmd

    - title: "Projects"
    
      contents:
        - section: "Projects"
          contents:
            - MNIST.qmd
            - project2.qmd
            - project3.qmd
 

format:
  html:
    theme: default
    css: styles.css

    
    toc: true
    
    smooth-scroll: true
    anchor-sections: true
    number-sections: true
    page-layout: article
    
    code-copy: false
    code-fold: show
    code-overflow: wrap
    code-tools:
      source: https://linkedin.com
      
      
    
    
    
    



