project:
  type: website
  output-dir: docs

website:

  sidebar:

    style: "docked"
    search: true
    contents:
      - "Data Science Projects"
      - "index.qmd"
    

  navbar:
    background: primary
    search: true
    tools:
      - icon: linkedin
        href: https://linkedin.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com
          - text: Report a Bug
            url:  https://bugs.com
    left:
      - text: "Projects"
        file: index.qmd
      - text: "About"
        file: about.qmd 
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



